spring.application.name=task-manager-spring-boot-run

# Mongo DB
spring.data.mongodb.uri=mongodb://taskmanager:pR0sb0FboS4@localhost:27017/taskmanager?authSource=admin

# JWT
jwt.secret=3d2848e8-b27e-4b6a-a53b-db14c58d40eb
